### PR TITLE
Todo-List

### PR DESCRIPTION
**Pull request by Wusinho**
This project is a Todo-List where you can create a new Project and create tasks that contain a title, date, and priority.

Built with:

 Bootstrap
- JavaScript
- Webpack
- Package.json

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @Wusinho! Your work with ES6+ modules and features is commendable. However, there are some requirement I'd like you to work on to complete this project. These include:
- [ ] Add the `.vscode` folder to your `.gitignore` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] A user should be able to edit and delete a given to-do item. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] The application should allow users to have different projects with separate lists of to-dos. Currently, after adding to-do items for the first project, I am unable to add to-do's for other projects. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list)). A single added to-do item tend to replicate itself several times without being attached to a specific project.
- [ ] A single to-do item should have 4 pieces of info i.e. a title, description, due date, and priority. Your to-dos have only 3 pieces of info. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/todo_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] Use localStorage to save todos between sessions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/localstorage_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list)). All created to-dos become undefined once I refresh the page. Please fix this.
- [ ] __[Optional]__ Deploy your app.

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

**Comment by rukundoeric** [comment]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - Follows gitwork-flow. 💯 
  - Codebase looks clean. 💯

- ### To Improve
  - [ ] [MANDATORY] `MIT` link from your readme is invalid(returning page not found).
  - [ ] [MANDATORY]  There is a bug in creating a task. whenever i create a task, it is showing `undefined and assign the record to all of the projects. Kindly fix that.
  Screen Shot 2021-06-01 at 23 21 27

  

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle:  :traffic_light: 

Hi @Wusinho, great job on this project :+1: Most of the functionality is implemented :1st_place_medal: However, let me kindly point out the comments that need to be addressed before approval. Kindly check the comments below:

- A single to-do item should have 4 pieces of info i.e. a title, description, due date, and priority. Your to-dos have only 3 pieces of info. Let us address this. This comment was pointed out earlier
- Kindly delete the .vscode and node_modules files and also check the path in the .gitignore file
- Webpack is not correctly configured, I get an error when I run the "npm run build-dev" command and also the "npm run start" command
bd

Kindly submit another code review request once these are addressed :smile: 
_Hapy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by rukundoeric** [comment]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow. 💯 
  - Codebase look clean and professinal. 💯 
  
- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
